// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 10. 27. 오후 3:03:56
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Projects/business/electric_circuit_web/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/plugins/**/*.{js,ts,mjs}","D:/Projects/business/electric_circuit_web/client/app/composables/**/*.{js,ts,mjs}","D:/Projects/business/electric_circuit_web/client/app/utils/**/*.{js,ts,mjs}","D:/Projects/business/electric_circuit_web/client/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Projects/business/electric_circuit_web/client/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;